### ISSUE TITLE
Assistance 

### ISSUE THREAD

**Issue by submeg** [imgrant/Last.fm2JRiver#1]
Hello imgrant,

I have been working on switching from iTunes to jRiver Media Centre. I wish to use my Android based phone (Samsung s5) as my portable player. Whilst doing some digging, I discovered that Android phones do not return play counts to jRiver. However, I can use last.fm to scrobble these plays and then pull these values back into jRiver (using this script).

I installed the .NET Scripting plugin and got that working. When I tried to use your script (LastfmPlayCount2JRiver.cs), it does not wish to compile. This I am sure,  is due to my inexperience with C# and scripting. 

My sequence of events:
1. I extracted the zip file and placed it into: C:\Program Files (x86)\J River\Media Center 22\Plugins\Last.fm2JRiver-master
2. I opened LastfmPlayCount2JRiver.cs in wordpad and copied across the script into a new Script in jRiver and ran it.
3. Returned the following errors below.

How do I go about getting this to work? Any assistance would be greatly appreciated. Thank you.

Regards,

Submeg

//ERROR TEXT:

Compiling Script...

Failure Compiling Script :-

C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(1,0) : error BC30689: Statement cannot appear outside of a method body.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(2,0) : error BC30689: Statement cannot appear outside of a method body.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(3,0) : error BC30689: Statement cannot appear outside of a method body.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(4,0) : error BC30689: Statement cannot appear outside of a method body.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(5,0) : error BC30689: Statement cannot appear outside of a method body.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(6,0) : error BC30689: Statement cannot appear outside of a method body.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(7,0) : error BC30689: Statement cannot appear outside of a method body.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(8,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(11,0) : error BC30481: 'Class' statement must end with a matching 'End Class'.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(11,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(12,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(13,0) : warning BC42020: Variable declaration without an 'As' clause; type of Object assumed.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(13,0) : error BC30205: End of statement expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(14,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(15,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(16,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(17,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(18,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(20,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(21,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(22,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(24,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(25,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(26,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(27,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(28,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(30,0) : error BC30689: Statement cannot appear outside of a method body.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(31,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(32,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(33,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(34,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(35,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(36,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(37,0) : error BC30188: Declaration expected.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(38,0) : error BC30035: Syntax error.
C:\J River\Media Center 22\Plugins\Script Plugin\Scripts\Last.fm Playcount.vb(39,0) : error BC30035: Syntax error.

 The Failure Occured
 In Class Object CSScriptLibrary
 when calling Method System.String Compile(System.String)
 
 The following Inner Exception was caused
 
 Everything that follows forms the stack Trace: 

   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.Compile(String scriptFile, String assemblyFile, Boolean debugBuild)
   at CSScriptLibrary.CSScript.CompileWithConfig(String scriptFile, String assemblyFile, Boolean debugBuild, String cssConfigFile)
   at ScriptRunner.ScriptRunner.Main(String[] args)

**Comment by imgrant** [comment]
From the name of your file ("Last.fm Playcount.vb"), it looks as though you are trying to compile a VB script, but this script is written in C#, you need to compile it as that.

Other than that, I'm afraid I no longer use JRiver, but I would hope that the scripting plugin is still compatible with the latest version.
